# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20141123_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post_title',
            field=models.CharField(blank=True, default='', max_length=101),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_title',
            field=models.CharField(max_length=101),
        ),
    ]
